// Publix perimeter-first walk order
// Deli/Bakery → Produce → Floral → Meat → Seafood → Dairy →
// Frozen → Beer/Wine → Pantry → Spices → Snacks → International →
// Beverages → Paper/Cleaning → Pet → Pharmacy → HBA

export const DEPARTMENTS = [
  { id:'deli',      label:'Deli & Bakery',         icon:'🥖', sub:'Entrance · front right',  kw:['deli','pub sub','sub sandwich','rotisserie','fried chicken','soup','hot bar','olive','pickle','hummus','salsa','guacamole','pesto','tapenade','bruschetta','bread','baguette','sourdough','rye','brioche','ciabatta','focaccia','naan','pita','roll','bagel','muffin','croissant','english muffin','flatbread','cornbread','biscuit','cake','pie','pastry','donut','cookie','brownie','danish','sushi','bakery item'] },
  { id:'produce',   label:'Produce',                icon:'🥬', sub:'Perimeter · back left',   kw:['apple','banana','orange','lemon','lime','grape','strawberry','blueberry','raspberry','blackberry','peach','pear','mango','avocado','tomato','cherry tomato','lettuce','romaine','spinach','kale','arugula','broccoli','cauliflower','carrot','celery','cucumber','zucchini','bell pepper','jalapeño','serrano','onion','garlic','ginger','potato','sweet potato','yam','mushroom','corn','asparagus','green bean','snap pea','herbs','mint','basil','cilantro','parsley','thyme','rosemary','scallion','green onion','shallot','beet','radish','fennel','artichoke','squash','butternut squash','pumpkin','watermelon','cantaloupe','honeydew','pineapple','papaya','kiwi','fig','plum','cherry','grapefruit','clementine','tangerine','pomegranate','bok choy','cabbage','brussels sprout','leek','eggplant','okra','turnip','parsnip','fresh fruit','fresh veg','organic produce','salad mix','bag salad'] },
  { id:'floral',    label:'Floral',                 icon:'🌸', sub:'Perimeter',               kw:['flower','bouquet','rose','lily','tulip','sunflower','orchid','plant','succulent','floral','arrangement','carnation','daisy','hydrangea','peony'] },
  { id:'meat',      label:'Meat',                   icon:'🥩', sub:'Perimeter · back',        kw:['chicken breast','chicken thigh','chicken wing','chicken leg','whole chicken','ground chicken','ground beef','ribeye','tenderloin','sirloin','t-bone','brisket','beef ribs','short rib','chuck roast','flank steak','skirt steak','strip steak','pork','ground pork','pork chop','pork loin','pork shoulder','pork belly','baby back ribs','spare ribs','lamb','lamb chop','leg of lamb','ground lamb','turkey breast','ground turkey','duck','veal','venison','bison','sausage','italian sausage','bratwurst','chorizo','andouille','kielbasa','bacon','ham','prosciutto','pancetta','salami','pepperoni','hot dogs','lunchmeat'] },
  { id:'seafood',   label:'Seafood',                icon:'🐟', sub:'Perimeter · back',        kw:['salmon','shrimp','tuna steak','tuna fillet','tilapia','cod','crab','lobster','scallop','oyster','clam','mussel','anchovy','sardine','halibut','flounder','mahi mahi','red snapper','rainbow trout','catfish','sea bass','branzino','sole','mackerel','crawfish','squid','calamari','octopus','caviar','lox','smoked salmon','imitation crab','fish fillet','seafood','shellfish'] },
  { id:'dairy',     label:'Dairy & Eggs',           icon:'🥛', sub:'Perimeter · right wall',  kw:['milk','whole milk','skim milk','2% milk','butter','unsalted butter','salted butter','cheese','cream cheese','cottage cheese','ricotta','mozzarella','parmesan','cheddar','brie','gouda','feta','gruyere','swiss cheese','provolone','colby','pepper jack','monterey jack','american cheese','eggs','dozen eggs','half and half','heavy cream','heavy whipping cream','sour cream','yogurt','greek yogurt','kefir','ghee','oat milk','almond milk','soy milk','coconut milk','buttermilk','whipped cream','crème fraîche','mascarpone','burrata','string cheese'] },
  { id:'frozen',    label:'Frozen Foods',           icon:'🧊', sub:'Back/left wall',          kw:['frozen pizza','frozen waffles','frozen pancakes','chicken nuggets','french fries','tater tots','onion rings','fish sticks','pot pie','frozen burrito','frozen edamame','frozen vegetables','frozen broccoli','frozen peas','frozen corn','frozen spinach','stir fry mix','frozen dinner','frozen entree','breakfast sandwich frozen','hash browns','egg rolls','spring rolls','frozen ravioli','frozen lasagna','ice cream','gelato','sorbet','sherbet','popsicle','frozen fruit','frozen berries'] },
  { id:'beer_wine', label:'Beer & Wine',            icon:'🍷', sub:'Left wall',               kw:['beer','lager','ale','ipa','stout','porter','pilsner','wheat beer','hard seltzer','white claw','truly','hard cider','wine','red wine','white wine','rosé','rosé wine','champagne','prosecco','sparkling wine','pinot noir','cabernet sauvignon','merlot','chardonnay','sauvignon blanc','riesling','pinot grigio','malbec','shiraz','zinfandel','sake','bourbon','whiskey','scotch','vodka','gin','rum','tequila','mezcal','brandy','cognac','vermouth','aperol','campari'] },
  { id:'pantry',    label:'Pantry & Dry Goods',     icon:'🥫', sub:'Center aisles 1–5',       kw:['pasta','spaghetti','penne','rigatoni','fettuccine','linguine','lasagna noodles','orzo','couscous','rice','arborio rice','jasmine rice','basmati rice','brown rice','wild rice','quinoa','farro','barley','lentils','black beans','kidney beans','chickpeas','cannellini beans','pinto beans','navy beans','all purpose flour','bread flour','almond flour','granulated sugar','brown sugar','powdered sugar','honey','maple syrup','agave','molasses','olive oil','vegetable oil','coconut oil','avocado oil','sesame oil','apple cider vinegar','balsamic vinegar','red wine vinegar','white vinegar','soy sauce','tamari','fish sauce','worcestershire sauce','hot sauce','sriracha','ketchup','mustard','dijon mustard','mayonnaise','relish','strawberry jam','jelly','peanut butter','almond butter','tahini','chicken broth','beef broth','vegetable broth','chicken stock','beef stock','tomato sauce','pasta sauce','marinara sauce','crushed tomatoes','diced tomatoes','tomato paste','coconut milk','baking powder','baking soda','active dry yeast','vanilla extract','cocoa powder','chocolate chips','breadcrumbs','panko','cornstarch','rolled oats','oatmeal','granola','breakfast cereal','grits','polenta','salt','black pepper','canned tuna','canned salmon','box of','can of','jar of'] },
  { id:'spices',    label:'Spices & Condiments',    icon:'🫙', sub:'Center aisles',           kw:['cumin','paprika','smoked paprika','turmeric','cayenne pepper','chili powder','coriander','cardamom','cinnamon','nutmeg','ground cloves','allspice','bay leaves','dried oregano','dried thyme','dried basil','dried rosemary','dried sage','dried dill','fennel seeds','garam masala','curry powder','za\'atar','old bay','cajun seasoning','italian seasoning','everything bagel seasoning','ranch dressing','caesar dressing','italian dressing','balsamic dressing','vinaigrette','bbq sauce','teriyaki sauce','hoisin sauce','oyster sauce','miso paste','harissa','sambal oelek','gochujang','chili crisp'] },
  { id:'snacks',    label:'Snacks & Candy',         icon:'🍿', sub:'Center aisles',           kw:['tortilla chips','potato chips','pretzels','microwave popcorn','rice cakes','crackers','graham crackers','goldfish crackers','pita chips','trail mix','almonds','cashews','walnuts','pecans','pistachios','peanuts','mixed nuts','sunflower seeds','pumpkin seeds','raisins','dried mango','dried cranberries','beef jerky','protein bar','granola bar','clif bar','kind bar','rxbar','candy','milk chocolate','dark chocolate','gummy bears','licorice','gum','breath mints'] },
  { id:'intl',      label:'International',          icon:'🌍', sub:'Center aisles',           kw:['taco shells','enchilada sauce','green chiles','adobo sauce','sofrito','goya','masala sauce','dal','ramen noodles','udon noodles','soba noodles','rice noodles','wonton wrappers','dumpling wrappers','kimchi','nori sheets','mirin','sake for cooking','dashi','paneer','chutney','falafel mix','grape leaves','tzatziki','harissa paste','international foods'] },
  { id:'beverages', label:'Beverages',              icon:'🥤', sub:'Center aisles',           kw:['bottled water','sparkling water','la croix','perrier','san pellegrino','topo chico','club soda','tonic water','orange juice','apple juice','cranberry juice','grape juice','lemonade','iced tea','sweet tea','gatorade','powerade','pedialyte','vitamin water','red bull','monster energy','celsius','ground coffee','whole bean coffee','espresso','cold brew','k-cups','nespresso pods','green tea','black tea','herbal tea','chai tea','matcha','hot chocolate mix','kombucha','protein shake','sports drink'] },
  { id:'paper',     label:'Paper & Cleaning',       icon:'🧹', sub:'Center aisles',           kw:['toilet paper','paper towels','facial tissue','kleenex','napkins','paper plates','plastic cups','ziploc bags','sandwich bags','storage bags','freezer bags','trash bags','garbage bags','aluminum foil','plastic wrap','parchment paper','wax paper','dish soap','dawn dish soap','dishwasher pods','laundry detergent','tide','fabric softener','dryer sheets','bleach','lysol','clorox wipes','windex','cleaning spray','all purpose cleaner','toilet bowl cleaner','drain cleaner','stain remover','febreze','air freshener','scented candle','sponges','scrub brush'] },
  { id:'pet',       label:'Pet',                    icon:'🐾', sub:'Center aisles',           kw:['dog food','cat food','pet food','dry kibble','wet cat food','wet dog food','dog treats','cat treats','rawhide','catnip','cat litter','pet shampoo','bird seed','fish food','puppy food','kitten food'] },
  { id:'pharmacy',  label:'Pharmacy & Health',      icon:'💊', sub:'Front · near entrance',   kw:['multivitamin','vitamin c','vitamin d','vitamin b12','fish oil','omega 3','probiotic','magnesium','zinc','iron supplement','calcium supplement','melatonin','protein powder','collagen powder','biotin','ibuprofen','tylenol','advil','aleve','aspirin','acetaminophen','antacid','tums','pepto bismol','nyquil','dayquil','mucinex','zyrtec','claritin','benadryl','sudafed','robitussin','band aids','first aid','neosporin','hydrogen peroxide','thermometer','sunscreen','pain reliever','allergy medicine','cough drops','throat lozenges'] },
  { id:'hba',       label:'Beauty & Personal Care', icon:'🧴', sub:'Front aisles',            kw:['shampoo','conditioner','dry shampoo','hair mask','hair dye','styling gel','hairspray','body wash','bar soap','face wash','facial cleanser','moisturizer','face lotion','body lotion','lip balm','chapstick','deodorant','antiperspirant','toothpaste','toothbrush','dental floss','mouthwash','disposable razors','razor blades','shaving cream','cologne','perfume','foundation','concealer','mascara','eyeliner','lipstick','nail polish','cotton balls','cotton swabs','q-tips','tampons','pads','contact lens solution','eye drops'] },
]

export const DEPT_ORDER = DEPARTMENTS.map(d => d.id)

export function categorizeToDept(name) {
  const lower = name.toLowerCase()
  for (const dept of DEPARTMENTS) {
    if (dept.kw.some(k => lower.includes(k))) return dept.id
  }
  return 'pantry'
}

export function getDept(id) {
  return DEPARTMENTS.find(d => d.id === id) ?? DEPARTMENTS.find(d => d.id === 'pantry')
}
