// ~200 curated Publix items for instant local autocomplete
export const COMMON_ITEMS = [
  // Produce
  {name:'Avocados',qty:'2',note:'ripe'},{name:'Bananas',qty:'1 bunch'},{name:'Baby spinach',qty:'5 oz bag'},{name:'Broccoli',qty:'1 head'},{name:'Cherry tomatoes',qty:'1 pint'},{name:'Garlic',qty:'1 head'},{name:'Ginger root',qty:'1 piece'},{name:'Jalapeños',qty:'2'},{name:'Kale',qty:'1 bunch'},{name:'Lemons',qty:'3'},{name:'Limes',qty:'4'},{name:'Onions',qty:'2'},{name:'Roma tomatoes',qty:'4'},{name:'Russet potatoes',qty:'3 lbs'},{name:'Shallots',qty:'2'},{name:'Sweet potatoes',qty:'2'},{name:'Yellow onion',qty:'1'},{name:'Blueberries',qty:'1 pint'},{name:'Strawberries',qty:'1 lb'},{name:'Raspberries',qty:'6 oz'},{name:'Apples',qty:'3'},{name:'Mangos',qty:'2'},{name:'Oranges',qty:'4'},
  // Meat
  {name:'Boneless chicken breasts',qty:'2 lbs'},{name:'Chicken thighs (bone-in)',qty:'2 lbs'},{name:'Chicken thighs (boneless)',qty:'1.5 lbs'},{name:'Ground beef (80/20)',qty:'1 lb'},{name:'Ground beef (93% lean)',qty:'1 lb'},{name:'Ground turkey',qty:'1 lb'},{name:'Italian sausage',qty:'1 lb'},{name:'Bacon',qty:'1 lb'},{name:'Pork tenderloin',qty:'1 lb'},{name:'Pork chops',qty:'4'},{name:'Ribeye steak',qty:'2'},{name:'Sirloin steak',qty:'2'},{name:'Baby back ribs',qty:'1 rack'},{name:'Whole roasted chicken',qty:'1'},
  // Seafood
  {name:'Salmon fillets',qty:'1 lb'},{name:'Shrimp (large, peeled)',qty:'1 lb'},{name:'Tuna steaks',qty:'2'},{name:'Cod fillets',qty:'1 lb'},{name:'Tilapia',qty:'1 lb'},{name:'Scallops',qty:'0.5 lb'},{name:'Lox (smoked salmon)',qty:'4 oz'},
  // Dairy
  {name:'Whole milk',qty:'1 gallon'},{name:'2% milk',qty:'1 gallon'},{name:'Oat milk',qty:'32 oz'},{name:'Almond milk',qty:'32 oz'},{name:'Large eggs',qty:'1 dozen'},{name:'Unsalted butter',qty:'1 lb'},{name:'Salted butter',qty:'1 lb'},{name:'Heavy cream',qty:'1 pint'},{name:'Half and half',qty:'1 pint'},{name:'Sour cream',qty:'16 oz'},{name:'Plain Greek yogurt',qty:'32 oz'},{name:'Cream cheese',qty:'8 oz'},{name:'Cottage cheese',qty:'16 oz'},{name:'Ricotta',qty:'15 oz'},{name:'Parmesan (block)',qty:'4 oz'},{name:'Parmesan (grated)',qty:'6 oz'},{name:'Sharp cheddar',qty:'8 oz'},{name:'Mozzarella (fresh)',qty:'8 oz'},{name:'Shredded mozzarella',qty:'8 oz'},{name:'Feta cheese',qty:'6 oz'},{name:'Brie',qty:'1 wheel'},{name:'Gouda',qty:'8 oz'},{name:'Pepper jack',qty:'8 oz'},
  // Deli/Bakery
  {name:'Sourdough bread',qty:'1 loaf'},{name:'Whole wheat bread',qty:'1 loaf'},{name:'Brioche buns',qty:'6 pack'},{name:'Flour tortillas',qty:'1 pack'},{name:'Corn tortillas',qty:'1 pack'},{name:'Pita bread',qty:'6 pack'},{name:'Naan',qty:'4 pack'},{name:'Bagels',qty:'6 pack'},{name:'English muffins',qty:'6 pack'},{name:'Croissants',qty:'4'},{name:'Pub Sub',qty:'1',note:'from deli'},
  // Frozen
  {name:'Frozen edamame',qty:'12 oz'},{name:'Frozen broccoli',qty:'12 oz'},{name:'Frozen peas',qty:'12 oz'},{name:'Frozen corn',qty:'12 oz'},{name:'Frozen berries',qty:'12 oz'},{name:'Vanilla ice cream',qty:'1 pint'},{name:'Frozen waffles',qty:'1 box'},
  // Beer/Wine
  {name:'Pinot noir',qty:'1 bottle'},{name:'Cabernet sauvignon',qty:'1 bottle'},{name:'Chardonnay',qty:'1 bottle'},{name:'Sauvignon blanc',qty:'1 bottle'},{name:'Rosé',qty:'1 bottle'},{name:'Prosecco',qty:'1 bottle'},{name:'Bourbon',qty:'1 bottle'},{name:'IPA (6-pack)',qty:'1'},{name:'Lager (6-pack)',qty:'1'},{name:'Hard seltzer (12-pack)',qty:'1'},
  // Pantry
  {name:'Olive oil (extra virgin)',qty:'1 bottle'},{name:'Avocado oil',qty:'1 bottle'},{name:'Soy sauce',qty:'1 bottle'},{name:'Apple cider vinegar',qty:'1 bottle'},{name:'Balsamic vinegar',qty:'1 bottle'},{name:'Chicken broth',qty:'32 oz'},{name:'Beef broth',qty:'32 oz'},{name:'Vegetable broth',qty:'32 oz'},{name:'Crushed tomatoes',qty:'28 oz can'},{name:'Diced tomatoes',qty:'14.5 oz can'},{name:'Tomato paste',qty:'6 oz can'},{name:'Marinara sauce',qty:'24 oz jar'},{name:'Canned black beans',qty:'15 oz'},{name:'Canned chickpeas',qty:'15 oz'},{name:'Canned coconut milk',qty:'13.5 oz'},{name:'Penne pasta',qty:'1 lb box'},{name:'Spaghetti',qty:'1 lb box'},{name:'Jasmine rice',qty:'2 lb bag'},{name:'Brown rice',qty:'2 lb bag'},{name:'Quinoa',qty:'1 lb bag'},{name:'All-purpose flour',qty:'5 lb'},{name:'Granulated sugar',qty:'4 lb'},{name:'Brown sugar',qty:'1 lb'},{name:'Honey',qty:'1 jar'},{name:'Maple syrup',qty:'1 bottle'},{name:'Peanut butter',qty:'16 oz'},{name:'Almond butter',qty:'16 oz'},{name:'Strawberry jam',qty:'1 jar'},{name:'Baking powder',qty:'1 can'},{name:'Baking soda',qty:'1 box'},{name:'Vanilla extract',qty:'2 oz'},{name:'Chocolate chips',qty:'12 oz'},{name:'Cocoa powder',qty:'8 oz'},{name:'Rolled oats',qty:'1 lb'},{name:'Granola',qty:'1 bag'},{name:'Panko breadcrumbs',qty:'8 oz'},{name:'Cornstarch',qty:'1 box'},{name:'Canned tuna',qty:'5 oz can'},
  // Spices/Condiments
  {name:'Kosher salt',qty:'1 box'},{name:'Black pepper',qty:'1 jar'},{name:'Cumin',qty:'1 jar'},{name:'Smoked paprika',qty:'1 jar'},{name:'Turmeric',qty:'1 jar'},{name:'Cayenne pepper',qty:'1 jar'},{name:'Chili powder',qty:'1 jar'},{name:'Cinnamon',qty:'1 jar'},{name:'Garlic powder',qty:'1 jar'},{name:'Onion powder',qty:'1 jar'},{name:'Italian seasoning',qty:'1 jar'},{name:'Old Bay',qty:'1 can'},{name:'Garam masala',qty:'1 jar'},{name:'Curry powder',qty:'1 jar'},{name:'Everything bagel seasoning',qty:'1 jar'},{name:'BBQ sauce',qty:'1 bottle'},{name:'Hot sauce',qty:'1 bottle'},{name:'Sriracha',qty:'1 bottle'},{name:'Ketchup',qty:'1 bottle'},{name:'Dijon mustard',qty:'1 jar'},{name:'Yellow mustard',qty:'1 bottle'},{name:'Mayonnaise',qty:'1 jar'},{name:'Ranch dressing',qty:'1 bottle'},{name:'Caesar dressing',qty:'1 bottle'},{name:'Teriyaki sauce',qty:'1 bottle'},{name:'Miso paste',qty:'1 jar'},{name:'Gochujang',qty:'1 jar'},{name:'Chili crisp',qty:'1 jar'},
  // Snacks
  {name:'Tortilla chips',qty:'1 bag'},{name:'Potato chips',qty:'1 bag'},{name:'Pretzels',qty:'1 bag'},{name:'Microwave popcorn',qty:'3 pack'},{name:'Crackers',qty:'1 box'},{name:'Goldfish crackers',qty:'1 bag'},{name:'Mixed nuts',qty:'1 can'},{name:'Almonds',qty:'1 bag'},{name:'Cashews',qty:'1 bag'},{name:'Pistachios',qty:'1 bag'},{name:'Trail mix',qty:'1 bag'},{name:'Granola bars',qty:'1 box'},{name:'Kind bars',qty:'1 box'},{name:'Dark chocolate',qty:'1 bar'},
  // Beverages
  {name:'Sparkling water (12-pack)',qty:'1'},{name:'La Croix (variety)',qty:'12 pack'},{name:'Orange juice',qty:'52 oz'},{name:'Cold brew coffee',qty:'32 oz'},{name:'Ground coffee',qty:'1 bag'},{name:'Green tea',qty:'1 box'},{name:'Kombucha',qty:'1 bottle'},{name:'Gatorade',qty:'4 pack'},{name:'Tonic water',qty:'1 bottle'},
  // Paper/Cleaning
  {name:'Toilet paper',qty:'1 pack'},{name:'Paper towels',qty:'1 pack'},{name:'Dish soap',qty:'1 bottle'},{name:'Dishwasher pods',qty:'1 pack'},{name:'Laundry detergent',qty:'1 bottle'},{name:'Trash bags',qty:'1 box'},{name:'Ziploc bags (gallon)',qty:'1 box'},{name:'Ziploc bags (quart)',qty:'1 box'},{name:'Aluminum foil',qty:'1 roll'},{name:'Parchment paper',qty:'1 roll'},{name:'Plastic wrap',qty:'1 roll'},{name:'Sponges',qty:'3 pack'},{name:'All-purpose cleaner',qty:'1 bottle'},{name:'Clorox wipes',qty:'1 canister'},
  // Pet
  {name:'Dog food',qty:'1 bag'},{name:'Cat food',qty:'1 bag'},{name:'Dog treats',qty:'1 bag'},{name:'Cat litter',qty:'1 bag'},
  // Pharmacy/HBA
  {name:'Ibuprofen',qty:'1 bottle'},{name:'Tylenol',qty:'1 bottle'},{name:'Multivitamin',qty:'1 bottle'},{name:'Vitamin D',qty:'1 bottle'},{name:'Melatonin',qty:'1 bottle'},{name:'Sunscreen SPF 50',qty:'1'},{name:'Shampoo',qty:'1 bottle'},{name:'Conditioner',qty:'1 bottle'},{name:'Body wash',qty:'1 bottle'},{name:'Deodorant',qty:'1'},{name:'Toothpaste',qty:'1'},{name:'Toothbrush',qty:'1'},{name:'Floss',qty:'1'},
]

export function getLocalSuggestions(query) {
  if (query.trim().length < 2) return []
  const q = query.toLowerCase()
  return COMMON_ITEMS.filter(item => item.name.toLowerCase().includes(q)).slice(0, 7)
}
